#!/bin/bash

vm=$1
ip=$2

if [[ $vm == "" || $ip == "" ]]; then
	echo "VM name and IP needed to continue"
	exit
fi

./lxc-prep -p /lxc/$vm -n $vm --ip $ip

lxc-start -n $vm -f $vm/config  -d

echo "Press Y/y to shutdown and destroy VM"

read a
if [[ $a == "Y" || $a == "y" ]]; then
        echo "Shutting down VM $vm"
	lxc-stop -n $vm
        rm -rf /lxc/$vm
fi

